# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.hostmanager.enabled = true
  config.hostmanager.include_offline = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.define "master.k8s" do |c|
    c.vm.hostname = "master.k8s"
    c.vm.network "private_network", ip: "192.168.0.10"
  end

  config.vm.define "node1.k8s" do |c|
    c.vm.hostname = "node1.k8s"
    c.vm.network "private_network", ip: "192.168.0.11"
  end

  config.vm.define "node2.k8s" do |c|
    c.vm.hostname = "node2.k8s"
    c.vm.network "private_network", ip: "192.168.0.12"
  end

  config.vm.provision :shell, path: "prepare-environment.sh"
end
